# Generated by Django 4.1.7 on 2023-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=2)),
                ('first', models.TextField()),
                ('last', models.TextField()),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('postcode', models.IntegerField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('offset', models.TextField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dob_date', models.TextField()),
                ('dob_age', models.TextField()),
                ('registered_date', models.TextField()),
                ('registered_age', models.TextField()),
                ('phone', models.TextField()),
                ('cell', models.TextField()),
                ('picture_large', models.TextField()),
                ('picture_medium', models.TextField()),
                ('picture_thumbnail', models.TextField()),
            ],
        ),
    ]
